#!/usr/bin/env python3
'WHY THIS EXISTS\n    ~/.claude/settings.json had `allow: ["Bash", ...]`, defaultMode=auto and NO deny\n    list at all, so nothing stopped `cat ~/.ssh/id_ed25519` or `cat ~/.aws/credentials`\n    from landing in a transcript that syncs to six machines and three git mirrors.\n    That sits badly against the op-gateway design, whose whole premise is that secrets\n    are rendered in memory and never written down (memory `op-gateway-single-door`).\n\n    The Claude-side `permissions.deny` block generated by home-settings-sync covers the\n    Read/Edit/Write TOOLS and fails CLOSED. This hook covers the SHELL, and copilot /\n    antigravity / opencode / pi / xcode get it too, because it is wired from\n    hooks-manifest.json rather than from one harness\'s settings file.\n\nWHY PYTHON AND NOT SH\n    The first cut embedded this logic in a `python3 - <<\'PY\'` heredoc inside a\n    `decision=$( ... )` command substitution, the same shape block-deploy.py\'s shell original used. It\n    would not parse: bash tracks quotes while scanning for the closing paren, the\n    regexes contain an odd number of apostrophes, and bash died on the next `(` with\n    "syntax error near unexpected token". block-deploy survives that shape only because\n    its apostrophes happen to balance. A pure-Python hook has no such trap.\n\nDESIGN\n    Deny only READS OF CONTENT. `ls -la ~/.ssh`, `stat`, `chmod 600`, `test -f` are\n    metadata operations an agent legitimately needs during setup and diagnosis;\n    blocking them teaches workarounds and nothing else. A command is denied when a\n    content-reader appears alongside a secret path, or a secret path is redirected\n    into stdin.\n\nLIMITS, STATED HONESTLY\n    This is a shell-string matcher, not a sandbox. A determined agent could build the\n    path from variables or base64 it. It raises the floor against the accident and the\n    careless case. The deny list, the op gateway, and human review are the other\n    layers. Do not treat it as a security boundary on its own.'
import json
import re
import sys



SECRET = re.compile(
    r"""(?ix)
      (?:^|[\s"'=:/])~?/?\.ssh/(?:id_[a-z0-9_]+(?!\.pub)\b|[^\s"';|&]*\.(?:pem|key)\b)
    | (?:^|[\s"'=:/])~?/?\.aws/credentials\b
    | (?:^|[\s"'=:/])~?/?\.git-credentials\b
    | (?:^|[\s"'=:/])~?/?\.docker/config\.json\b
    | (?:^|[\s"'=:/])~?/?\.netrc\b
    | (?:^|[\s"'=:/])~?/?\.pgpass\b
    | Library/Keychains/
    | (?:^|[\s"'=:/])[^\s"';|&]*\.env\.protected\b
    | (?:^|[\s"'=:/])[^\s"';|&]*/service-account[^\s"';|&]*\.json\b
    """
)


READER = re.compile(
    r"""(?ix)
    (?:^|[;&|]|\$\(|\x60)\s*
    (?:sudo\s+)?
    (?:cat|bat|less|more|head|tail|strings|xxd|od|hexdump|base64|nl|tac|rev
      |cp|mv|scp|rsync|tar|zip|gzip|install
      |grep|egrep|fgrep|rg|ag|ack|awk|sed|jq|yq|cut|sort|uniq|tr
      |curl|wget|nc|ncat|socat|ssh
      |python3?|perl|ruby|node|php
      |openssl|gpg|security)\b
    """
)


REDIRECT_IN = re.compile(
    r"<\s*[^\s<>|;&]*"
    r"(?:\.ssh/id_|\.aws/credentials|\.git-credentials|\.netrc|\.pgpass|\.env\.protected)"
)

REASON = (
    "BLOCKED by block-secret-read: this command would read credential material into "
    "the transcript.\n\n"
    "Transcripts sync across the fleet and the store pushes to GitHub + s1/s2/ls within "
    "seconds, so a secret that reaches one is effectively published. Secrets are rendered "
    "in memory through the op gateway and are never written down - see memory "
    "`op-gateway-single-door`.\n\n"
    "What still works:\n"
    "  * Metadata is fine: ls, stat, test -f, chmod, mkdir on these paths are NOT blocked.\n"
    "  * Need a secret VALUE? Go through the op gateway (`op read ...`), which is audited.\n"
    "  * Need the user to run something that touches a key? Hand them the exact command "
    "to run with the `!` prefix.\n\n"
    "Do not route around this by renaming, base64-ing, or rebuilding the path from "
    "variables. If the block is wrong for a legitimate case, say so and let the user decide."
)


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0  
    cmd = (data.get("tool_input") or {}).get("command", "") or ""
    if not cmd.strip() or not SECRET.search(cmd):
        return 0
    if not (READER.search(cmd) or REDIRECT_IN.search(cmd)):
        return 0  
    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": REASON,
            }
        },
        sys.stdout,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
