#!/usr/bin/env python3
"project-materialize.py -- reconstitute a working repo's canonical .agents/ store\nfrom the agent-context store (projects/<name>/), then rebuild the .claude/\nharness projection via agents-materialize.py.\n\nThis is the store -> .agents half of the materialization pipeline -- the half\nthat was missing. Without it, .agents/ drifts from the store: store entities\nnever reach disk (an added command/skill stays invisible), and skills present\nonly in .claude/ get silently deleted on the next agents-materialize (which\nclean-replaces .claude/ from an incomplete .agents/). This closes the loop so\nthe harness projection always reflects the store.\n\nA disk file under an owned subtree that the store no longer projects is retired\n(deleted, after being copied into the same materialize-rescue batch used for\noverwrites) when the manifest proves materialize wrote it and it was never\nedited since -- otherwise it is kept and reported as disk-only, as always. See\nclassify() and write_manifest().\n\nScope: behavior-driving entities only -- commands, skills, agents (subagents),\nscripts, hooks. Docs/memory/instructions are served live by the MCP server\nstraight from the store, so they are always correct regardless of disk and are\nnot projected here (any by-path .agents/docs tree a project keeps is untouched).\n\nStore file format: each .md entity carries a leading store-frontmatter block\n(the one with `uuid:`); it is stripped so the harness sees its native\nfrontmatter. Scripts/hooks are raw content + a .meta.toml sidecar (dropped);\nthe exec bit lives in the sidecar, so it is restored on projection.\n\nIdempotent, device-agnostic (no absolute paths beyond $HOME), safe to re-run --\nincluding as a SessionStart hook (runs before agents-materialize).\n\nUsage:\n  project-materialize.py [<project-dir>]   # default: $CLAUDE_PROJECT_DIR or $PWD\n  project-materialize.py --check [<dir>]   # report drift, write nothing (exit 3 if drift)\n\nObservations guarded: #321."
import glob
import hashlib
import io
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import frontmatter_strip
import harness_paths as hp
import store_mcp

HOME = os.environ.get("HOME", os.path.expanduser("~"))



OWNED = ["claude/commands", "claude/skills", "claude/agents", "scripts", "hooks", "parity", "ship"]



PARTIAL = ("parity", "ship")

PRUNE_DIR_NAMES = {".git", "node_modules", "obj", "bin", "build", ".gradle", "Pods"}

STALE_STORE_RE = re.compile(r"agents\.db|agent-db|the agent database")

GENERATED_MARKER_TEXT = "GENERATED FILE — the canonical copy lives in the agent-context store"

GLOBAL_TWIN_DIR = {
    "claude/agents": "agents",
    "claude/skills": "skills",
    "claude/commands": "commands",
    "scripts": "scripts",
    "hooks": "hooks",
}

MARKER = "<!-- generated by agent-context · project-materialize.py · edit the STORE, not this file -->"




def read_toml_all(path, key):
    'Every value of `key = "..."` in path, newline-joined (sed -n \'s/^key.../\\1/p\', no head).'
    if not os.path.isfile(path):
        return ""
    pattern = re.compile(r'^' + re.escape(key) + r' *= *"(.*)"')
    found = []
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                m = pattern.match(line.rstrip("\n"))
                if m:
                    found.append(m.group(1))
    except OSError:
        return ""
    return "\n".join(found)


def read_toml_first(path, key):
    all_ = read_toml_all(path, key)
    return all_.splitlines()[0] if all_ else ""




def url_identifies_repo(u, r):
    'Does a remote url identify this repo, compared on a PATH BOUNDARY (never a bare substring).'
    if u.endswith(".git"):
        u = u[:-4]
    if r.endswith(".git"):
        r = r[:-4]
    if not r:
        return False
    if u == r:
        return True
    if u.endswith("/" + r):
        return True
    if u.endswith(":" + r):
        return True
    return False


def resolve_project(directory, store):
    base = os.path.basename(directory)
    if os.path.isfile(os.path.join(store, "projects", base, "project.toml")):
        return base
    proc = subprocess.run(["git", "-C", directory, "config", "--get-all", "remote.origin.url"],
                          capture_output=True, text=True)
    urls = proc.stdout if proc.returncode == 0 else ""
    if not urls.strip():
        return None
    matches = []
    for pt in sorted(glob.glob(os.path.join(store, "projects", "*", "project.toml"))):
        cr = read_toml_all(pt, "canonical_remote")
        if not cr:
            continue
        repo = cr.split(":", 1)[1] if ":" in cr else cr
        name = os.path.basename(os.path.dirname(pt))
        for url in urls.splitlines():
            if not url:
                continue
            if url_identifies_repo(url, repo):
                if name not in matches:
                    matches.append(name)
                break
    if not matches:
        return None
    if len(matches) > 1:
        print("project-materialize: REFUSING - %s matches more than one store project (%s). "
              "Fix the duplicate canonical_remote." % (directory, " ".join(matches)), file=sys.stderr)
        return None
    return matches[0]


def is_git_repo(directory):
    if os.path.isdir(os.path.join(directory, ".git")):
        return True
    proc = subprocess.run(["git", "-C", directory, "rev-parse", "--git-dir"], capture_output=True)
    return proc.returncode == 0


def logical_pwd(path):
    '`cd "$path" 2>/dev/null && pwd || echo "$path"` -- logical, symlink-preserving pwd.'
    proc = subprocess.run(["bash", "-c", 'cd "$1" 2>/dev/null && pwd || echo "$1"', "_", path],
                          capture_output=True, text=True)
    return proc.stdout.rstrip("\n")




def scrub(path):
    'Drop store-only artifacts (*.meta.toml, *.meta.json, .DS_Store, __pycache__) from a projection.'
    if not os.path.isdir(path):
        return
    for dirpath, dirnames, filenames in os.walk(path, topdown=False):
        for fname in filenames:
            if fname.endswith(".meta.toml") or fname.endswith(".meta.json") or fname == ".DS_Store":
                try:
                    os.remove(os.path.join(dirpath, fname))
                except OSError:
                    pass
        for dname in dirnames:
            if dname == "__pycache__":
                shutil.rmtree(os.path.join(dirpath, dname), ignore_errors=True)


def strip_fm(root):
    frontmatter_strip.strip_frontmatter_tree([root])


def make_executable(path, skip_md=False):
    if not os.path.isdir(path):
        return
    for dirpath, _dirnames, filenames in os.walk(path):
        for fname in filenames:
            if skip_md and fname.endswith(".md"):
                continue
            full = os.path.join(dirpath, fname)
            try:
                st = os.stat(full)
                os.chmod(full, st.st_mode | 0o111)
            except OSError:
                pass


def stamp_generated(root):
    "Scripts and hooks only: a .md entity's first line is load-bearing frontmatter,\n    and prepending to it would break how every harness parses a skill."
    if not os.path.isdir(root):
        return
    for dirpath, _dirnames, filenames in os.walk(root):
        for fname in filenames:
            if fname.endswith(".md"):
                continue
            f = os.path.join(dirpath, fname)
            try:
                with open(f, "rb") as fh:
                    data = fh.read()
            except OSError:
                continue
            if GENERATED_MARKER_TEXT.encode("utf-8") in data:
                continue
            try:
                text = data.decode("utf-8")
            except UnicodeDecodeError:
                continue
            lines = text.split("\n")
            first = lines[0] if lines else ""
            banner = ("# GENERATED FILE — the canonical copy lives in the agent-context store.\n"
                      "# Edit it there (upsert_script / upsert_hook / edit_body), not here: this copy is\n"
                      "# overwritten at every SessionStart and after every store write, and an edit made\n"
                      "# here disappears with nothing announcing it (audit policy).\n")
            if first.startswith("#!"):
                new_text = first + "\n" + banner + "\n".join(lines[1:])
            else:
                new_text = banner + text
            tmp = f + ".gen"
            with open(tmp, "w", encoding="utf-8") as fh:
                fh.write(new_text)
            os.replace(tmp, f)


def build_into(stage, sub, rel, kind, base):
    'Build one target subtree from a store entity dir into $STAGE (mirrors .agents layout).'
    src = os.path.join(base, sub)
    dst = os.path.join(stage, rel)
    if not os.path.isdir(src):
        return
    os.makedirs(dst, exist_ok=True)
    shutil.copytree(src, dst, dirs_exist_ok=True, copy_function=shutil.copy2)
    scrub(dst)
    if kind == "content":
        strip_fm(dst)
    else:
        stamp_generated(dst)
        make_executable(dst)




def files_differ(a, b):
    '`diff -q` semantics: missing destination counts as differing.'
    if not os.path.isfile(b):
        return True
    try:
        with open(a, "rb") as fa, open(b, "rb") as fb:
            return fa.read() != fb.read()
    except OSError:
        return True


def walk_files(root):
    result = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for fname in sorted(filenames):
            result.append(os.path.join(dirpath, fname))
    return result


def is_partial(rel):
    return rel in PARTIAL


def global_twin(rel, r):
    'Does a disk-only path under an owned subtree correspond to a GLOBAL store entity?'
    d = GLOBAL_TWIN_DIR.get(rel)
    if d is None:
        return False
    return os.path.exists(os.path.join(HOME, ".agent-context", "global", d, r))


def is_vendored_skill(live, rel, r):
    'A skill that ships its own references/ corpus came from upstream and belongs on disk.'
    if rel != "claude/skills":
        return False
    skill = r.split("/", 1)[0]
    if skill == r:
        return False
    return os.path.isdir(os.path.join(live, skill, "references"))


def sha256_of(path):
    try:
        h = hashlib.sha256()
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
    except OSError:
        return ""


def manifest_sha(manifest, key):
    if not os.path.isfile(manifest):
        return ""
    try:
        with open(manifest, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                parts = line.split()
                if len(parts) >= 2 and parts[1] == key:
                    return parts[0]
    except OSError:
        pass
    return ""


def classify(stage, ag):
    'Store files to add/update vs disk-only files to preserve, plus retirement candidates.\n\n    A disk-only file under an owned subtree is retired (deleted on apply, rescued first)\n    only when the manifest says materialize wrote it and its sha256 still matches: nobody\n    edited it since, so a store rename/removal is the only way it got here. A file with no\n    manifest entry, or whose sha no longer matches, is always kept and reported as disk-only,\n    exactly as before this existed.'
    updates = 0
    extras = 0
    shadows = 0
    retiring = 0
    extra_list = []
    shadow_list = []
    replaced_list = []
    rescue_list = []
    retire_list = []
    manifest = os.path.join(ag, "tmp", ".materialize-manifest")
    for rel in OWNED:
        staged = os.path.join(stage, rel)
        live = os.path.join(ag, rel)
        if os.path.isdir(staged):
            for f in walk_files(staged):
                r = os.path.relpath(f, staged)
                live_f = os.path.join(live, r)
                if files_differ(f, live_f):
                    updates += 1
                    if os.path.exists(live_f):
                        replaced_list.append(".agents/%s/%s" % (rel, r))
                        recorded = manifest_sha(manifest, "%s/%s" % (rel, r))
                        if recorded:
                            if sha256_of(live_f) != recorded:
                                rescue_list.append("%s/%s" % (rel, r))
                        elif os.path.getmtime(live_f) > os.path.getmtime(f):
                            rescue_list.append("%s/%s" % (rel, r))
        if not os.path.isdir(live):
            continue
        if is_partial(rel):
            continue
        for f in walk_files(live):
            r = os.path.relpath(f, live)
            if r.endswith(".DS_Store") or r.endswith(".meta.toml"):
                continue
            if is_vendored_skill(live, rel, r):
                continue
            if not os.path.exists(os.path.join(staged, r)):
                if global_twin(rel, r):
                    shadows += 1
                    shadow_list.append(".agents/%s/%s" % (rel, r))
                else:
                    recorded = manifest_sha(manifest, "%s/%s" % (rel, r))
                    if recorded and sha256_of(f) == recorded:
                        retiring += 1
                        retire_list.append("%s/%s" % (rel, r))
                    else:
                        extras += 1
                        extra_list.append(".agents/%s/%s" % (rel, r))
    return {
        "updates": updates, "extras": extras, "shadows": shadows, "retiring": retiring,
        "extra_list": extra_list, "shadow_list": shadow_list,
        "replaced_list": replaced_list, "rescue_list": rescue_list, "retire_list": retire_list,
    }




def warn_if_stale(path, label):
    if not os.path.isfile(path):
        return
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            content = fh.read()
    except OSError:
        return
    if not STALE_STORE_RE.search(content):
        return
    print("  ⚠ %s names the RETIRED store (~/.agents/agents.db via the agent-db MCP server)." % label,
          file=sys.stderr)
    print("    The store is ~/.agent-context, served by agent-context. Delete this file and", file=sys.stderr)
    print("    re-run to have a correct one generated — it is untracked and regenerated here.", file=sys.stderr)


def owned_by_us(path):
    if not os.path.isfile(path):
        return False
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            head = "".join(fh.readline() for _ in range(3))
    except OSError:
        return False
    return "generated by agent-context" in head


def claude_imports_agents(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if line.startswith("@AGENTS.md"):
                    return True
    except OSError:
        pass
    return False


def pointer_audit(directory):
    for fname in ("AGENTS.md", "CLAUDE.md"):
        path = os.path.join(directory, fname)
        if not os.path.exists(path):
            print("  ⚠ missing bootstrap pointer: %s" % fname, file=sys.stderr)
            continue
        warn_if_stale(path, fname)
    claude = os.path.join(directory, "CLAUDE.md")
    if os.path.isfile(claude) and not claude_imports_agents(claude) and not owned_by_us(claude):
        print("  ⚠ CLAUDE.md is hand-written and does not import AGENTS.md, so Claude Code cannot see it.",
              file=sys.stderr)
        print("    Add '@AGENTS.md' as its first line, or delete it and re-run to have this generate one.",
              file=sys.stderr)


def report_extras(extra_list, shadow_list):
    for e in extra_list:
        print("  ⚠ disk-only, not in store (kept — reconcile via upsert_*): %s" % e)
    for e in shadow_list:
        print("  ⚠ SHADOWS a global store entity of the same name (kept, but this disk copy WINS at "
              "runtime — diff it against the global original and delete it, or upsert it to project "
              "scope on purpose): %s" % e)


def report_orphaned_vendored_skills(ag, stage):
    live = os.path.join(ag, "claude", "skills")
    staged = os.path.join(stage, "claude", "skills")
    if not os.path.isdir(live):
        return True
    n = 0
    for name in sorted(os.listdir(live)):
        d = os.path.join(live, name)
        if not os.path.isdir(d):
            continue
        skill = name
        if not os.path.isdir(os.path.join(d, "references")):
            continue
        if not os.path.isfile(os.path.join(d, "SKILL.md")):
            continue
        if os.path.exists(os.path.join(staged, skill, "SKILL.md")):
            continue
        if global_twin("claude/skills", "%s/SKILL.md" % skill):
            continue
        n += 1
        print("  ⚠ ORPHANED vendored skill — invocable, and in no store scope, so no context audit "
              "can see it: .agents/claude/skills/%s. If it was retired, delete the directory (here and in "
              ".claude/); `upsert_*` is the wrong advice for a vendored corpus because the next re-sync "
              "reverts it." % skill)
    return n == 0


def git_ignored(directory, paths):
    'The subset of `paths` (absolute, under `directory`) that git ignores or excludes\n    there. Empty when git cannot answer, so a failure hides nothing.'
    rels = [os.path.relpath(p, directory) for p in paths if p != directory]
    if not rels:
        return set()
    try:
        p = subprocess.run(["git", "-C", directory, "check-ignore", "-z", "--stdin"],
                           input="\0".join(rels) + "\0", capture_output=True, text=True,
                           timeout=30)
    except (OSError, subprocess.SubprocessError):
        return set()
    return {os.path.join(directory, r) for r in p.stdout.split("\0") if r}


def report_stray_harness_dirs(directory):
    'A harness dir anywhere but the repo root is served in preference to the projected one.'
    found = []
    worktrees = {os.path.join(directory, scope, "worktrees") for scope in (hp.AGENTS_DIRNAME, hp.CLAUDE_DIRNAME)}
    for dirpath, dirnames, _filenames in os.walk(directory):
        keep = []
        for name in sorted(dirnames):
            full = os.path.join(dirpath, name)
            if name in PRUNE_DIR_NAMES or full in worktrees:
                continue
            keep.append(name)
            if name in (hp.CLAUDE_DIRNAME, hp.AGENTS_DIRNAME):
                found.append(full)
        dirnames[:] = keep
    exclude = {hp.project_claude_dir(directory), hp.project_agents_dir(directory)}
    found = [d for d in found if d not in exclude]
    ignored = git_ignored(directory, sorted({os.path.dirname(d) for d in found}))
    n = 0
    for d in found:
        parent = os.path.dirname(d)
        
        
        if parent in ignored or os.path.lexists(os.path.join(parent, ".git")):
            continue
        try:
            entries = [e for e in os.listdir(d) if e != "tmp"]
        except OSError:
            entries = []
        if not entries:
            continue
        n += 1
        rel = d[len(directory) + 1:] if d.startswith(directory + os.sep) else d
        print("  ⚠ STRAY harness directory outside the repo root — the harness serves it in "
              "preference to the projection whenever work touches its subtree, and it is in no store scope, "
              "so no audit can see it: %s" % rel)
    return n == 0


def report_shadowed(directory):
    'A store entity that shadows a file the repo already tracks. Reported, never refused.'
    proc = subprocess.run(["git", "-C", directory, "rev-parse", "--is-inside-work-tree"], capture_output=True)
    if proc.returncode != 0:
        return
    tracked_proc = subprocess.run(["git", "-C", directory, "ls-files"], capture_output=True, text=True)
    if tracked_proc.returncode != 0:
        return
    tracked = tracked_proc.stdout
    if not tracked.strip():
        return
    tracked_lines = tracked.splitlines()
    shown = False
    for sub in ("hooks", "scripts"):
        d = os.path.join(directory, ".agents", sub)
        if not os.path.isdir(d):
            continue
        for base in sorted(os.listdir(d)):
            full = os.path.join(d, base)
            if not os.path.isfile(full):
                continue
            if base.endswith(".meta.toml") or base.endswith(".meta.json"):
                continue
            regex = re.compile(r'(^|/)' + re.escape(base) + r'$')
            hits = [t for t in tracked_lines if regex.search(t)]
            if not hits:
                continue
            if not shown:
                print("  ⚠ store entities that shadow a file this repo already tracks:")
                shown = True
            print("      %s — the repo also tracks: %s" % (base, " ".join(hits)))
    if shown:
        print("      One of the two is the real one, and they will drift. If the repo's copy")
        print("      is canonical, delete the store entity; if the store's is, delete the")
        print("      repo's and stop tracking it.")


def report_replaced(directory, replaced_list, rescue_list, rescue_dir):
    for e in replaced_list:
        print("  · replaced from store: %s" % e)
    if not rescue_dir:
        return
    lines = [
        "",
        "  ################################################################",
        "  ##  Local edits were overwritten by the store projection      ##",
        "  ################################################################",
    ]
    for e in rescue_list:
        lines.append("  ##  overwritten: .agents/%s" % e)
    rel_rescue = rescue_dir[len(directory) + 1:] if rescue_dir.startswith(directory + os.sep) else rescue_dir
    lines += [
        "  ##",
        "  ##  Your versions are saved here (nothing was lost):",
        "  ##    %s" % rel_rescue,
        "  ##",
        "  ##  Do one of these now, before continuing:",
        "  ##   1. Keep the work: read the rescued file and promote it into the",
        "  ##      store with upsert_script / upsert_hook / edit_body. The store",
        "  ##      is canonical — an edit that lives only in .agents/ is deleted",
        "  ##      by the next projection, which is what just happened here.",
        "  ##   2. Discard it: delete the rescue directory above.",
        "  ##  Leaving it untouched loses the work at the next projection.",
        "  ################################################################",
        "",
    ]
    for line in lines:
        print(line, file=sys.stderr)


def report_retired(retired_list, rescue_dir, directory):
    if not retired_list:
        return
    rel_rescue = rescue_dir[len(directory) + 1:] if rescue_dir.startswith(directory + os.sep) else rescue_dir
    for e in retired_list:
        print("  · retired (no longer in store, rescued to %s first): .agents/%s" % (rel_rescue, e))


def write_manifest(ag, stage):
    'Record what was just projected, so the NEXT run can tell our own output from an edit somebody made.'
    tmp_dir = os.path.join(ag, "tmp")
    try:
        os.makedirs(tmp_dir, exist_ok=True)
    except OSError:
        return
    tmp = os.path.join(tmp_dir, ".materialize-manifest.tmp")
    manifest = os.path.join(tmp_dir, ".materialize-manifest")
    try:
        with open(tmp, "w", encoding="utf-8") as fh:
            for rel in OWNED:
                staged = os.path.join(stage, rel)
                if not os.path.isdir(staged):
                    continue
                for f in walk_files(staged):
                    sub = os.path.relpath(f, staged)
                    fh.write("%s  %s/%s\n" % (sha256_of(f), rel, sub))
    except OSError:
        return
    try:
        os.replace(tmp, manifest)
    except OSError:
        pass




def render_agents_md(project, facts):
    facts_line = facts if facts else "No stack recorded in the store."
    lines = [
        MARKER,
        "",
        "# %s" % project,
        "",
        facts_line,
        "",
        "All instructions, memory and documentation for this repository live in the **agent-context",
        "store** (`~/.agent-context`) — plain files in a git repo, served by the `agent-context` MCP",
        "server. There is no database, and this file is deliberately not a second copy of them.",
        "",
        "**First turn: call `get_session_context` with this working directory.** It returns this",
        "project's instructions, its memory index, open audit observations and the current machine's",
        "identity. Follow what it returns.",
        "",
        "If that tool is not available to you, say so plainly rather than proceeding on guesses. This",
        "repository does not restate its own rules here, so working without the store means working",
        "without them.",
    ]
    return "\n".join(lines) + "\n"


def render_claude_md():
    lines = [
        "@AGENTS.md",
        "",
        MARKER,
        "<!-- Claude Code reads CLAUDE.md and NOT AGENTS.md, so this file exists only to import it:",
        "     https://code.claude.com/docs/en/memory#agentsmd . Shared content belongs in AGENTS.md,",
        "     via the store, so every harness gets it. Claude-only content may be added below the",
        "     import — but prefer the store, which reaches every harness. Block-level HTML comments",
        "     are stripped before this file enters context, so these lines cost nothing. -->",
    ]
    return "\n".join(lines) + "\n"


def replace_with(path, text):
    
    
    
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), prefix=os.path.basename(path) + ".",
                               suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise


def write_bootstrap_pointers(directory, project, pstore):
    facts = []
    stack = read_toml_all(os.path.join(pstore, "project.toml"), "stack")
    if stack:
        facts.append("stack `%s`" % stack)
    branch = read_toml_all(os.path.join(pstore, "project.toml"), "integration_branch")
    if branch:
        facts.append("integration branch `%s`" % branch)
    workspace = read_toml_all(os.path.join(pstore, "project.toml"), "workspace")
    if workspace:
        facts.append("workspace `%s`" % workspace)
    facts_str = " · ".join(facts)

    a_path = os.path.join(directory, "AGENTS.md")
    if not os.path.exists(a_path) or owned_by_us(a_path):
        replace_with(a_path, render_agents_md(project, facts_str))
    else:
        print("  ⚠ AGENTS.md is hand-written — left untouched. Fold it into the store if it should "
              "be generated.", file=sys.stderr)
        warn_if_stale(a_path, "AGENTS.md")

    c_path = os.path.join(directory, "CLAUDE.md")
    if not os.path.exists(c_path) or owned_by_us(c_path):
        replace_with(c_path, render_claude_md())
    elif claude_imports_agents(c_path):
        warn_if_stale(c_path, "CLAUDE.md")
    else:
        print("  ⚠ CLAUDE.md is hand-written and does not import AGENTS.md, so Claude Code cannot see it.",
              file=sys.stderr)
        print("    Add '@AGENTS.md' as its first line, or delete it and re-run to have this generate one.",
              file=sys.stderr)
        warn_if_stale(c_path, "CLAUDE.md")


def assert_git_exclude(directory, project):
    'Nothing agent-related is ever committed into a project repo. Excluded via .git/info/exclude.'
    git_dir = os.path.join(directory, ".git")
    if not os.path.isdir(git_dir):
        return
    excl = os.path.join(git_dir, "info", "exclude")
    try:
        os.makedirs(os.path.dirname(excl), exist_ok=True)
    except OSError:
        pass
    existing_lines = set()
    existing_text = ""
    if os.path.isfile(excl):
        try:
            with open(excl, encoding="utf-8", errors="replace") as fh:
                existing_text = fh.read()
        except OSError:
            existing_text = ""
        existing_lines = set(existing_text.splitlines())
    if "agent-context generated (never commit)" not in existing_text:
        try:
            with open(excl, "a", encoding="utf-8") as fh:
                fh.write("\n# --- agent-context generated (never commit) ---------------------------\n")
                fh.write("# Written by project-materialize.py; regenerated every session, per machine.\n")
            print("project-materialize[%s]: added agent-generated files to .git/info/exclude" % project)
        except OSError:
            pass
    for pat in ("/AGENTS*.md", "/CLAUDE*.md*", "/buildServer.json", "/.compile",
                ".agents/", hp.CLAUDE_DIRNAME + "/", ".opencode/", "/opencode.json",
                "/.claudeignore", "/.cgcignore", ".orca/", "/mcp.json"):
        if pat not in existing_lines:
            try:
                with open(excl, "a", encoding="utf-8") as fh:
                    fh.write(pat + "\n")
                existing_lines.add(pat)
            except OSError:
                pass
    for f in ("AGENTS.md", "CLAUDE.md", "buildServer.json", ".compile", ".agents", hp.CLAUDE_DIRNAME):
        proc = subprocess.run(["git", "-C", directory, "ls-files", "--", f], capture_output=True, text=True)
        tracked = proc.stdout
        if not tracked.strip():
            continue
        print("  ⚠ %s is TRACKED in git — agent-generated files must not be committed." % f,
              file=sys.stderr)
        for line in tracked.splitlines():
            print("        %s" % line, file=sys.stderr)
        print("    Untrack the paths listed above:  git rm --cached -- <path>…   (then commit)",
              file=sys.stderr)




def phr(component, flag, detail=None):
    script = os.path.join(hp.scripts_dir(HOME), "health-record.py")
    if not os.path.isfile(script):
        return
    args = [sys.executable, script, component, flag]
    if detail is not None:
        args.append(detail)
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        subprocess.run(args, stderr=subprocess.DEVNULL)
    except OSError:
        pass









SCOPE_EVIDENCE_LIMIT = 8
SCOPE_ROOTS = ("projects", "workspaces")


class ScopeFetchRefused(Exception):
    'A reason safe to print: never carries the token or a response body.'


def scope_key_is_safe(key):
    'No empty, `.` or `..` segment, not absolute, no trailing slash; a projects/ or\n    workspaces/ key also needs a file below its scope directory.'
    if not isinstance(key, str) or not key or "\x00" in key or "\\" in key or key.startswith("/"):
        return False
    parts = key.split("/")
    if any(part in ("", ".", "..") for part in parts):
        return False
    return len(parts) >= 3 or parts[0] not in SCOPE_ROOTS


def scope_repo_evidence(directory):
    '(repo_root, marker id or None, remote urls) for the repo at directory, or None.'
    ev = store_mcp.repo_evidence(directory)
    if not ev["marker_id"] and not ev["remotes"]:
        return None
    return ev["cwd"], ev["marker_id"], ev["remotes"]


def scope_write_atomic(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".pmfetch.", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise


def scope_remove_empty_dirs(store, path):
    'Remove emptied parents of path, up to (not including) the store root.'
    parent = os.path.dirname(path)
    while parent != store and parent.startswith(store + os.sep):
        try:
            os.rmdir(parent)
        except OSError:
            return
        parent = os.path.dirname(parent)


def scope_drop_files(store, keys, digests, protected):
    'Delete recorded files whose bytes still equal what was written and no live record lists.'
    for key in keys:
        if key in protected or not scope_key_is_safe(key) or key.split("/")[0] not in SCOPE_ROOTS:
            continue
        path = os.path.join(store, key)
        if not os.path.realpath(os.path.dirname(path)).startswith(os.path.realpath(store) + os.sep):
            continue  
        try:
            with open(path, "rb") as fh:
                current = hashlib.sha256(fh.read()).hexdigest()
        except OSError:
            continue
        if digests.get(key) != current:
            continue
        try:
            os.remove(path)
        except OSError:
            continue  
        scope_remove_empty_dirs(store, path)


def scope_read_record(path):
    '(record, digests) or None for a missing or malformed record.'
    try:
        with open(path, encoding="utf-8") as fh:
            record = json.load(fh)
    except (OSError, ValueError):
        return None
    if not isinstance(record, dict) or not isinstance(record.get("keys"), list):
        return None
    digests = record.get("digests") if isinstance(record.get("digests"), dict) else {}
    return record, digests


def scope_request(env, project, remotes):
    "The response's projects/ and workspaces/ keys; refuses the whole response on any unsafe key."
    try:
        bundle = store_mcp.call("get_materialized",
                                {"project": [project] if project else [], "remote": list(remotes)},
                                env=env)
    except (store_mcp.ToolError, store_mcp.StoreUnreachable) as exc:
        raise ScopeFetchRefused(str(exc))
    if not isinstance(bundle, dict) or not all(isinstance(k, str) and isinstance(v, str)
                                               for k, v in bundle.items()):
        raise ScopeFetchRefused("response is not a string map")
    if not all(scope_key_is_safe(k) for k in bundle):
        raise ScopeFetchRefused("response has an unsafe key")
    return {k: v for k, v in bundle.items() if k.split("/")[0] in SCOPE_ROOTS}


def scope_first_toml_value(text, key):
    m = re.search(r'^' + re.escape(key) + r' *= *"(.*)"', text, re.M)
    return m.group(1) if m else ""


def relay_configured():
    'A relay machine: host and token are known. A store with neither is read as it stands.'
    env = store_mcp.relay_env()
    return bool(env["AGENT_CONTEXT_HOST"] and env["AGENT_CONTEXT_TOKEN"])


def store_is_checkout(store):
    return os.path.exists(os.path.join(store, ".git")) or os.path.isdir(os.path.join(store, "server"))


def scope_fetch(directory, scope_tmp):
    "Fetch the cwd project's projects/ and workspaces/ keys into a per-run temp tree and return\n    its path, or None when there is nothing to ask. The path is appended to scope_tmp first, so\n    the caller deletes it even when this raises."
    env = store_mcp.relay_env()
    if not env["AGENT_CONTEXT_HOST"] or not env["AGENT_CONTEXT_TOKEN"]:
        return None
    if not os.path.isdir(directory):
        return None
    evidence = scope_repo_evidence(directory)
    if evidence is None:
        return None
    _root, marker, urls = evidence
    bundle = scope_request(env, marker, urls[:SCOPE_EVIDENCE_LIMIT - (1 if marker else 0)])

    created = []
    temp_root = os.environ.get("TMPDIR")
    if not temp_root:
        agents_tmp = os.path.join(directory, ".agents", "tmp")
        for path in (os.path.dirname(agents_tmp), agents_tmp):
            if not os.path.isdir(path):
                os.makedirs(path, exist_ok=True)
                created.append(path)
        temp_root = agents_tmp
    tree = tempfile.mkdtemp(prefix="pmscope.", dir=temp_root)
    scope_tmp.append((tree, tuple(created)))
    real_tree = os.path.realpath(tree)
    for key in bundle:
        if not os.path.realpath(os.path.dirname(os.path.join(tree, key))).startswith(real_tree + os.sep):
            raise ScopeFetchRefused("response has an unsafe key")
    for key, text in sorted(bundle.items()):
        scope_write_atomic(os.path.join(tree, key), text.encode("utf-8"))
    return tree


def scope_retire_legacy(store):
    "Delete what an older version wrote under the store's projects/ and workspaces/: each file\n    a record lists whose bytes still equal the digest it holds, then the record itself."
    record_dir = os.path.join(HOME, ".cache", "agent-context", "project-scope")
    try:
        names = sorted(os.listdir(record_dir))
    except OSError:
        return
    for name in names:
        if not name.endswith(".json"):
            continue
        path = os.path.join(record_dir, name)
        got = scope_read_record(path)
        if got:
            scope_drop_files(store, [k for k in got[0]["keys"] if isinstance(k, str)], got[1], set())
        try:
            os.remove(path)
        except OSError:
            pass
    try:
        os.rmdir(record_dir)
    except OSError:
        pass


def scope_sweep_ds_store(store):
    "Remove dirs under the store's projects/ and workspaces/ that hold nothing but Finder's\n    .DS_Store files (what a retire leaves on macOS), the .DS_Store files with them. Bottom-up, so a\n    dir emptied by its children's removal goes too. The store root, a symlinked dir and a\n    symlinked .DS_Store are never touched, and a dir with any other entry keeps its .DS_Store."
    for root_name in SCOPE_ROOTS:
        root = os.path.join(store, root_name)
        if os.path.islink(root) or not os.path.isdir(root):
            continue
        for dirpath, _dirnames, _filenames in os.walk(root, topdown=False, followlinks=False):
            if os.path.islink(dirpath):
                continue
            try:
                entries = os.listdir(dirpath)
            except OSError:
                continue
            
            
            if not entries or any(e != ".DS_Store" or os.path.islink(os.path.join(dirpath, e))
                                  or not os.path.isfile(os.path.join(dirpath, e)) for e in entries):
                continue
            for e in entries:
                try:
                    os.remove(os.path.join(dirpath, e))
                except OSError:
                    break
            try:
                os.rmdir(dirpath)
            except OSError:
                pass




def parse_args(argv):
    check = False
    directory = None
    for a in argv:
        if a == "--check":
            check = True
        elif a.startswith("-"):
            print("project-materialize: unknown flag %s" % a, file=sys.stderr)
            sys.exit(2)
        else:
            directory = a
    return check, directory


def main():
    scope_tmp = []
    
    signal.signal(signal.SIGTERM, lambda _signum, _frame: sys.exit(143))
    try:
        return run(scope_tmp)
    finally:
        for tree, created in scope_tmp:
            shutil.rmtree(tree, ignore_errors=True)
            for path in reversed(created):
                try:
                    os.rmdir(path)
                except OSError:
                    pass


def run(scope_tmp):
    argv = sys.argv[1:]
    
    
    
    if any(a in ("-h", "--help") for a in argv):
        print(__doc__)
        return 0
    check, dir_arg = parse_args(argv)

    store = os.environ.get("AGENT_CONTEXT_STORE") or os.path.join(HOME, ".agent-context")

    directory = dir_arg or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    if directory.endswith("/"):
        directory = directory[:-1]
    
    
    
    directory = logical_pwd(directory)

    
    
    
    scope = store
    if relay_configured():
        try:
            scope = scope_fetch(directory, scope_tmp)
        except Exception as exc:
            reason = str(exc) if isinstance(exc, ScopeFetchRefused) else type(exc).__name__
            print("project-materialize: project scope fetch failed (%s); projection unchanged"
                  % reason, file=sys.stderr)
            return 1
        if scope is not None and not check and not store_is_checkout(store):
            scope_retire_legacy(store)
            scope_sweep_ds_store(store)

    if scope is None or not os.path.isdir(os.path.join(scope, "projects")):
        print("project-materialize: no store at %s" % store, file=sys.stderr)
        return 0
    if not os.path.isdir(directory):
        print("project-materialize: no dir %s" % directory, file=sys.stderr)
        return 0

    project = resolve_project(directory, scope)
    if not project:
        
        
        if os.path.realpath(directory) == os.path.realpath(store):
            return 0
        if is_git_repo(directory):
            print("project-materialize: %s is a git repo but matches no store project — its skills, "
                  "commands and hooks are not projected here. Onboard it, or fix its canonical_remote."
                  % directory)
        return 0

    
    
    proj_toml = os.path.join(scope, "projects", project, "project.toml")
    if not check and os.path.isfile(proj_toml):
        p_uuid = read_toml_first(proj_toml, "uuid")
        p_name = read_toml_first(proj_toml, "display_name")
        if p_uuid:
            marker = os.path.join(directory, ".agents", "project-id")
            want_lines = [
                "# agent-context project marker: machine-agnostic project identity.",
                "# `id` is the stable project UUID; resolve_project prefers this over the git",
                "# remote, so mirrors, renamed remotes, and linked worktrees all resolve alike.",
                "# WRITTEN by project-materialize.py from the store. Never committed; never edited",
                "# by hand: a change here is overwritten on the next session.",
                'id = "%s"' % p_uuid,
                'display_name = "%s"' % (p_name or project),
            ]
            want = "\n".join(want_lines)
            existing = None
            if os.path.isfile(marker):
                try:
                    with open(marker, encoding="utf-8", errors="replace") as fh:
                        existing = fh.read().rstrip("\n")
                except OSError:
                    existing = None
            if existing is None or existing != want:
                os.makedirs(os.path.dirname(marker), exist_ok=True)
                with open(marker, "w", encoding="utf-8") as fh:
                    fh.write(want + "\n")
                print("project-materialize[%s]: wrote .agents/project-id from the store" % project)

    
    
    print("project-materialize[%s]: resolved from %s" % (project, directory))
    pstore = os.path.join(scope, "projects", project)

    ws = read_toml_all(os.path.join(pstore, "project.toml"), "workspace")
    wstore = ""
    if ws and os.path.isdir(os.path.join(scope, "workspaces", ws)):
        wstore = os.path.join(scope, "workspaces", ws)

    stage = tempfile.mkdtemp(prefix="pmat.", dir=os.environ.get("TMPDIR", "/tmp"))
    try:
        if wstore:
            build_into(stage, "skills", "claude/skills", "content", wstore)
            build_into(stage, "commands", "claude/commands", "content", wstore)
            print("project-materialize[%s]: including workspace '%s' skills/commands" % (project, ws))

        build_into(stage, "commands", "claude/commands", "content", pstore)
        build_into(stage, "skills", "claude/skills", "content", pstore)
        build_into(stage, "agents", "claude/agents", "content", pstore)
        build_into(stage, "scripts", "scripts", "raw", pstore)
        build_into(stage, "docs/parity", "parity", "content", pstore)
        build_into(stage, "docs/ship", "ship", "content", pstore)
        build_into(stage, "hooks", "hooks", "raw", pstore)

        ag = os.path.join(directory, ".agents")
        result = classify(stage, ag)
        updates = result["updates"]
        extras = result["extras"]
        shadows = result["shadows"]
        retiring = result["retiring"]
        extra_list = result["extra_list"]
        shadow_list = result["shadow_list"]
        replaced_list = result["replaced_list"]
        rescue_list = result["rescue_list"]
        retire_list = result["retire_list"]

        if check:
            print("project-materialize[%s]: %d store file(s) to add/update, %d disk-only, "
                  "%d shadowing a global entity, %d pending retirement"
                  % (project, updates, extras, shadows, retiring))
            report_extras(extra_list, shadow_list)
            for e in retire_list:
                print("  ⚠ pending retirement (materialize wrote it, unedited, no longer in "
                      "store; apply deletes it, rescued first): .agents/%s" % e)
            stray = 0
            if not report_orphaned_vendored_skills(ag, stage):
                stray = 1
            if not report_stray_harness_dirs(directory):
                stray = 1
            pointer_audit(directory)
            for e in rescue_list:
                print("  ⚠ disk copy is NEWER than the store's and an apply would replace it: .agents/%s"
                      % e, file=sys.stderr)
            if updates == 0 and extras == 0 and shadows == 0 and stray == 0 and retiring == 0:
                print("  ✓ in sync with store")
                return 0
            return 3

        
        rescue_dir = ""
        retired_list = []
        if rescue_list or retire_list:
            stamp = time.strftime("%Y%m%d-%H%M%S")
            rescue_dir = os.path.join(ag, "tmp", "materialize-rescue", stamp)
            for r in rescue_list + retire_list:
                src = os.path.join(ag, r)
                dst = os.path.join(rescue_dir, r)
                try:
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    shutil.copy2(src, dst)
                except OSError:
                    pass
            
            base = os.path.join(ag, "tmp", "materialize-rescue")
            try:
                batches = sorted((d for d in os.listdir(base) if os.path.isdir(os.path.join(base, d))),
                                 reverse=True)
            except OSError:
                batches = []
            for old in batches[20:]:
                shutil.rmtree(os.path.join(base, old), ignore_errors=True)
            
            
            for r in retire_list:
                try:
                    os.remove(os.path.join(ag, r))
                    retired_list.append(r)
                except OSError:
                    pass

        
        
        copy_failed = []
        for rel in OWNED:
            staged = os.path.join(stage, rel)
            live = os.path.join(ag, rel)
            if not os.path.isdir(staged):
                continue
            os.makedirs(live, exist_ok=True)
            for dirpath, dirnames, _filenames in os.walk(staged):
                for dname in dirnames:
                    full = os.path.join(dirpath, dname)
                    os.makedirs(os.path.join(live, os.path.relpath(full, staged)), exist_ok=True)
            for f in walk_files(staged):
                sub = os.path.relpath(f, staged)
                dst = os.path.join(live, sub)
                tmpf = os.path.join(os.path.dirname(dst), ".pm-tmp-%s.%d" % (os.path.basename(dst), os.getpid()))
                try:
                    shutil.copy2(f, tmpf)
                    os.replace(tmpf, dst)
                except OSError:
                    try:
                        os.remove(tmpf)
                    except OSError:
                        pass
                    copy_failed.append("%s/%s" % (rel, sub))
        if copy_failed:
            print("project-materialize: could not project:%s" % "".join(" " + x for x in copy_failed),
                  file=sys.stderr)

        write_manifest(ag, stage)

        for rel in OWNED:
            scrub(os.path.join(ag, rel))
        for rel in ("scripts", "hooks"):
            make_executable(os.path.join(ag, rel), skip_md=True)

        if updates != 0 or extras != 0 or retiring != 0:
            print("project-materialize[%s]: overlaid %d store file(s) onto .agents; %d disk-only kept, "
                  "%d shadowing a global entity, %d retired"
                  % (project, updates, extras, shadows, len(retired_list)))
            report_stray_harness_dirs(directory)
        report_extras(extra_list, shadow_list)
        
        
        report_orphaned_vendored_skills(ag, stage)
        report_replaced(directory, replaced_list, rescue_list, rescue_dir)
        report_retired(retired_list, rescue_dir, directory)
        report_shadowed(directory)
    finally:
        shutil.rmtree(stage, ignore_errors=True)

    
    write_bootstrap_pointers(directory, project, pstore)

    
    assert_git_exclude(directory, project)

    
    sys.stdout.flush()
    sys.stderr.flush()
    proc = subprocess.run([sys.executable, os.path.join(store, "global", "scripts", "lsp-plugin-guard.py"), directory])
    if proc.returncode == 0:
        phr("lsp-plugin-guard", "--ok")
    else:
        phr("lsp-plugin-guard", "--fail",
            "lsp-plugin-guard.py failed for %s, so this project's enabledPlugins was not reconciled. "
            "A project-scoped entry silently overrides the global one, so an LSP plugin the fleet retired "
            "can still be running here — and disabling it globally is not evidence it is off." % directory)

    sys.stdout.flush()
    sys.stderr.flush()
    proc = subprocess.run([sys.executable, os.path.join(store, "global", "scripts", "project-settings-sync.py"),
                           directory])
    if proc.returncode == 0:
        phr("project-settings-sync", "--ok")
    else:
        phr("project-settings-sync", "--fail",
            "project-settings-sync.py failed for %s, so .agents/claude/settings.json was not reconciled "
            "with the store. This project's own hook wiring (worktree seeding, sweep, post-edit format) "
            "may be stale or missing, and if the file did not exist it was not created." % directory)

    sys.stdout.flush()
    sys.stderr.flush()
    proc = subprocess.run([sys.executable, os.path.join(store, "global", "scripts", "agents-materialize.py"), directory])
    if proc.returncode == 0:
        phr("agents-materialize", "--ok")
    else:
        phr("agents-materialize", "--fail",
            "agents-materialize.py failed for %s, so .claude/ was not rebuilt from .agents/. Everything the "
            "harness actually reads in this project — hooks, commands, settings — is whatever the "
            "last successful run left behind, however old." % directory)

    return 0


if __name__ == "__main__":
    
    
    
    if isinstance(sys.stdout, io.TextIOWrapper):
        sys.stdout.reconfigure(line_buffering=True)
    if isinstance(sys.stderr, io.TextIOWrapper):
        sys.stderr.reconfigure(line_buffering=True)
    sys.exit(main())
